name: iron_db
description: "A simple and convenient key-value database."
version: 0.0.2
repository: https://github.com/AoEiuV020/FlutterIronDB/tree/main/packages/iron_db

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
